from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Optional, Sequence, Union

import numpy as np


ImageSelector = Union[int, str]
AtomSelector = Union[str, Sequence[int], None]


@dataclass(frozen=True)
class DimerVectorResult:
    path: Path
    image_index: int
    selected_indices: list[int]
    raw_norm: float
    image_selection: str


def write_dimer_vector_from_images(
    images,
    path: Union[str, Path],
    *,
    image: ImageSelector = "auto",
    atoms: AtomSelector = "active",
    active_atoms: Sequence[int] = (),
    frozen_atoms: Sequence[int] = (),
    zero_frozen_atoms: bool = True,
    normalize: bool = True,
    scale: float = 1.0,
    energy_log: Optional[Union[str, Path]] = None,
    image_prefix: str = "image",
) -> DimerVectorResult:
    """Write a CP2K &DIMER_VECTOR block from a NEB image list.

    The core routine intentionally depends only on ASE-like Atoms objects and
    plain options so it can be reused outside the full nebmake workflow.
    """
    image_index, image_selection = resolve_dimer_image_index(
        images, image=image, energy_log=energy_log
    )
    vector = tangent_from_neighbor_images(images, image_index)
    selected_indices = resolve_atom_indices(
        len(images[image_index]),
        atoms=atoms,
        active_atoms=active_atoms,
        frozen_atoms=frozen_atoms,
        zero_frozen_atoms=zero_frozen_atoms,
    )
    vector = mask_vector(vector, selected_indices)
    raw_norm = float(np.linalg.norm(vector))
    if raw_norm <= 0.0:
        raise ValueError(
            "DIMER_VECTOR is zero after atom selection. "
            "Use atoms: all, provide active_atoms, or disable zero_frozen_atoms."
        )
    if normalize:
        vector = vector / raw_norm
    vector = vector * float(scale)

    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    text = format_dimer_vector(
        vector,
        comments=[
            "Generated by neb-helper.",
            "Place this block inside MOTION / GEO_OPT / TRANSITION_STATE / DIMER.",
            f"Direction: MIC/Cartesian({image_prefix}_{image_index + 1:03d} - {image_prefix}_{image_index - 1:03d}).",
            f"TS guess image: {image_prefix}_{image_index:03d} (0-based index {image_index}; {image_selection}).",
            f"Selected atom count: {len(selected_indices)} of {len(images[image_index])}.",
        ],
    )
    path.write_text(text, encoding="utf-8")
    return DimerVectorResult(
        path=path,
        image_index=image_index,
        selected_indices=selected_indices,
        raw_norm=raw_norm,
        image_selection=image_selection,
    )


def resolve_dimer_image_index(
    images, *, image: ImageSelector = "auto", energy_log: Optional[Union[str, Path]] = None
) -> tuple[int, str]:
    n_images = len(images)
    if n_images < 3:
        raise ValueError("At least three images are required to build a DIMER_VECTOR.")

    if isinstance(image, str):
        mode = image.lower().replace("-", "_")
        if mode in {"auto", "max_energy", "highest_energy"}:
            energy_index = _highest_internal_energy_index(energy_log, n_images)
            if energy_index is not None:
                return energy_index, "highest internal energy from energy log"
            if mode != "auto":
                raise ValueError(
                    "DIMER_VECTOR image selection needs neb_relax.energy_log, "
                    f"but no usable energy log was found: {energy_log}"
                )
            return _middle_internal_image_index(n_images), "middle image fallback"
        if mode in {"middle", "mid"}:
            return _middle_internal_image_index(n_images), "middle image"
        raise ValueError(
            "Unsupported dimer_vector.image value. Use auto, middle, max_energy, or a 0-based integer."
        )

    index = int(image)
    _validate_internal_image_index(index, n_images)
    return index, "user-selected image"


def tangent_from_neighbor_images(images, image_index: int) -> np.ndarray:
    _validate_internal_image_index(image_index, len(images))
    left = images[image_index - 1]
    right = images[image_index + 1]
    return _mic_displacement(
        left.get_positions(),
        right.get_positions(),
        images[image_index].cell.array,
        images[image_index].get_pbc(),
    )


def resolve_atom_indices(
    n_atoms: int,
    *,
    atoms: AtomSelector = "active",
    active_atoms: Sequence[int] = (),
    frozen_atoms: Sequence[int] = (),
    zero_frozen_atoms: bool = True,
) -> list[int]:
    if atoms is None:
        selected = list(range(n_atoms))
    elif isinstance(atoms, str):
        mode = atoms.lower()
        if mode == "all":
            selected = list(range(n_atoms))
        elif mode == "active":
            selected = list(active_atoms) if active_atoms else list(range(n_atoms))
        else:
            raise ValueError("Unsupported dimer_vector.atoms value. Use all, active, or a list.")
    else:
        selected = [int(index) for index in atoms]

    _validate_atom_indices(selected, n_atoms)
    selected_set = set(selected)
    if zero_frozen_atoms:
        frozen = [int(index) for index in frozen_atoms]
        _validate_atom_indices(frozen, n_atoms)
        selected_set.difference_update(frozen)
    return sorted(selected_set)


def mask_vector(vector: np.ndarray, selected_indices: Sequence[int]) -> np.ndarray:
    masked = np.zeros_like(vector, dtype=float)
    if selected_indices:
        masked[list(selected_indices)] = vector[list(selected_indices)]
    return masked


def format_dimer_vector(vector: np.ndarray, comments: Sequence[str] = ()) -> str:
    lines = [f"! {comment}" for comment in comments]
    lines.append("&DIMER_VECTOR")
    for x, y, z in np.asarray(vector, dtype=float):
        lines.append(f"  {x: .12e}  {y: .12e}  {z: .12e}")
    lines.append("&END DIMER_VECTOR")
    return "\n".join(lines) + "\n"


def _highest_internal_energy_index(
    energy_log: Optional[Union[str, Path]], n_images: int
) -> Optional[int]:
    if not energy_log:
        return None
    path = Path(energy_log)
    if not path.exists():
        return None
    lines = [line.strip() for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]
    if not lines:
        return None
    tokens = lines[-1].split()
    if len(tokens) < n_images + 1:
        return None
    try:
        energies = [float(token) for token in tokens[1 : n_images + 1]]
    except ValueError:
        return None
    internal_energies = energies[1:-1]
    if not internal_energies:
        return None
    return int(np.argmax(internal_energies)) + 1


def _middle_internal_image_index(n_images: int) -> int:
    return max(1, min(n_images - 2, n_images // 2))


def _validate_internal_image_index(index: int, n_images: int) -> None:
    if index <= 0 or index >= n_images - 1:
        raise ValueError(
            "DIMER_VECTOR needs an internal image because it uses image-1 and image+1. "
            f"Got index {index} for {n_images} images."
        )


def _validate_atom_indices(indices: Sequence[int], n_atoms: int) -> None:
    bad = [index for index in indices if index < 0 or index >= n_atoms]
    if bad:
        raise ValueError(f"Atom indices out of range for {n_atoms} atoms: {bad}")


def _mic_displacement(pos_a, pos_b, cell, pbc) -> np.ndarray:
    pos_a = np.asarray(pos_a, dtype=float)
    pos_b = np.asarray(pos_b, dtype=float)
    cell = np.asarray(cell, dtype=float)
    pbc = np.asarray(pbc, dtype=bool)
    delta = pos_b - pos_a
    if not np.any(pbc):
        return delta
    delta_frac = delta @ np.linalg.inv(cell)
    for axis, is_periodic in enumerate(pbc):
        if is_periodic:
            delta_frac[..., axis] -= np.round(delta_frac[..., axis])
    return delta_frac @ cell
